### ISSUE TITLE
Crash trying to load title page

### ISSUE THREAD

**Issue by Laura7089** [sebsauvage/Shaarli#252]
I get the following error through my browser:

```
An unexpected error happened, and the error template could not be displayed.

base64_decode() expects parameter 1 to be string, bool given
/var/www/shaarli/application/bookmark/BookmarkIO.php91
#0 /var/www/shaarli/application/bookmark/BookmarkIO.php(91): base64_decode()
#1 /var/www/shaarli/application/bookmark/BookmarkFileService.php(80): Shaarli\Bookmark\BookmarkIO->read()
#2 /var/www/shaarli/application/container/ContainerBuilder.php(101): Shaarli\Bookmark\BookmarkFileService->__construct()
#3 /var/www/shaarli/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}()
#4 /var/www/shaarli/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet()
#5 /var/www/shaarli/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get()
#6 /var/www/shaarli/application/container/ContainerBuilder.php(114): Slim\Container->__get()
#7 /var/www/shaarli/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}()
#8 /var/www/shaarli/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet()
#9 /var/www/shaarli/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get()
#10 /var/www/shaarli/application/front/controller/visitor/ErrorController.php(20): Slim\Container->__get()
#11 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke()
#12 /var/www/shaarli/vendor/slim/slim/Slim/App.php(728): call_user_func_array()
#13 /var/www/shaarli/vendor/slim/slim/Slim/App.php(396): Slim\App->handlePhpError()
#14 /var/www/shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#15 /var/www/shaarli/index.php(196): Slim\App->run()
#16 {main}
```

Shaarli log reads:

```
shaarli_1             | 172.54.0.1 - - [17/Aug/2022:21:27:26 +0000] "GET / HTTP/1.1" 200 1848 "-" "Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0"
shaarli_1             | 2022/08/17 21:27:26 [error] 13#13: *1 open() "/var/www/shaarli/images/favicon.ico" failed (2: No such file or directory), client: 172.54.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "BASEURL", referrer: "BASEURL"
shaarli_1             | 172.54.0.1 - - [17/Aug/2022:21:27:26 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "https://BASEURL/" "Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0"
```

I'm using docker image `shaarli/shaarli` with sha `22019f84ad35`

**Comment by ArthurHoaro** [comment]
Please look for solutions or open your issue on github.com/shaarli/Shaarli instead.
